Reimplement auth
cityofaustin/atd-moped pull request #102
Opened 2020-10-28 06:11 UTC by mateoclarke

2020-10-28 19:55 UTC, mddilley approved these changes
This looks amazing! I'm glad to see similar patterns to the auth context in VZE and also that it can be done with Cognito all the same. The memoization in the context taught me a new trick, and the user custom hook sets up a great base to role based permissions as well! I logged in with my staging username with no issues at all.

I ran into one problem when first running locally, but it was an easy fix to get up and running. 👍 
<img width="456" alt="Screen Shot 2020-10-28 at 12 30 36 PM" src="https://user-images.githubusercontent.com/37249039/97489299-6265e600-192d-11eb-9cbc-5b1547362a25.png">

2020-10-28 19:55 UTC, mddilley commented on moped-editor/src/views/auth/LoginView.js
>            <Formik
Here's Formik! Maybe we could swap out these login and register forms to be powered by React Hook Form, but they would perfectly fine as is. 👍

2020-10-28 19:55 UTC, mddilley commented on moped-editor/src/views/auth/LoginView.js
> +      setErrors({ password: err.message });
Nice! I tried out an incorrect password, and I received the error message.

2020-10-28 19:55 UTC, mddilley commented on moped-editor/src/auth/user.js
> +  const values = React.useMemo(() => ({ user, login, logout }), [user]);
This is cool! Glad to see a solution to the problem that we all discussed on Monday about potential performance cost. Might be cool add to VZE one day too.

2020-10-28 22:44 UTC, sergiogcx requested changes
It won't run for me:

![2020-10-28_17-42-22](https://user-images.githubusercontent.com/5282430/97504616-35253200-1945-11eb-8fc1-926ee9260d3d.png)

2020-10-29 20:38 UTC, mateoclarke commented
> It won't run for me:
> 
> ![2020-10-28_17-42-22](https://user-images.githubusercontent.com/5282430/97504616-35253200-1945-11eb-8fc1-926ee9260d3d.png)

Thanks @sergiogcx, Mike also pointed this out but I just pushed the code that should fix this import error.

2020-10-29 20:40 UTC, merged