Add UI to select component tags
cityofaustin/atd-moped pull request #1049
Opened 2023-05-15 19:29 UTC by chiaberry

## Associated issues

## Testing
**URL to test:** 

**Steps to test:**

---
#### Ship list
- [ ] Code reviewed 
- [ ] Product manager approved
- [ ] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable

2023-05-16 18:15 UTC, johnclary requested changes
Looks great and works great ✨ 

Just a few minor changes then 🚢 🚢 🚢 🚢 🚢

2023-05-16 18:15 UTC, johnclary commented on moped-editor/src/views/projects/projectView/ProjectComponents/utils/form.js
> +      label: `${tag.type.charAt(0).toUpperCase() + tag.type.slice(1)} - ${
i like what you did here—but i also think we should fix this at the DB level. would you nix this the case handling and i'll fix the "type" values? i'm going to open a migration for that momentarily now that i have new tag values from NW.

2023-05-16 18:15 UTC, johnclary commented on moped-editor/src/views/projects/projectView/ProjectComponents/EditAttributesModal.js
> +  console.log(componentToEdit)
❌

2023-05-16 18:15 UTC, johnclary commented on moped-editor/src/views/projects/projectView/ProjectComponents/EditAttributesModal.js
> +  console.log(initialFormValues)
❌

2023-05-16 18:15 UTC, johnclary commented on moped-database/migrations/1683927220054_run_sql_migration/up.sql
> +ALTER TABLE moped_proj_component_tags ADD CONSTRAINT unique_component_and_tag UNIQUE ("project_component_id", "component_tag_id");
nice!

2023-05-16 18:17 UTC, johnclary commented on moped-editor/src/views/projects/projectView/ProjectComponents/ComponentForm.js
> +        </Grid>
i think we should up the contrast on the highlights of the already-selected items. I feel like that's out of scope for this issue—i'll make a separate snackoo for it.

<img width="763" alt="Screenshot 2023-05-16 at 2 16 34 PM" src="https://github.com/cityofaustin/atd-moped/assets/14793120/5611afd7-7d2d-4591-94f3-47fd6dfa75c6">

2023-05-16 19:05 UTC, johnclary commented on moped-editor/src/views/projects/projectView/ProjectComponents/utils/form.js
> +      label: `${tag.type.charAt(0).toUpperCase() + tag.type.slice(1)} - ${
as promised: https://github.com/cityofaustin/atd-moped/pull/1051

2023-05-16 22:47 UTC, roseeichelmann approved these changes
test steps worked perfectly ✨

2023-05-17 13:35 UTC, johnclary approved these changes
fantastic—thank you @chiaberry!

you mind holding off on a merge until we bring https://github.com/cityofaustin/atd-moped/pull/1051 along?

edit: ✅ 🚢

2023-05-17 16:25 UTC, frankhereford requested changes
Chia, this is great, thank you. It works perfectly when editing, but I think that it's not saving tags from the create component modal. I've got a little recording, if this is helpful. 

https://github.com/cityofaustin/atd-moped/assets/3653206/38ca386a-ed05-4b69-8e0e-9177123c8a7f

Please let me know if I'm missing anything, and I'll flip this to approve in a heartbeat.

Thanks!!

2023-05-17 16:38 UTC, chiaberry commented
@frankhereford thank you! i will investigate

2023-05-18 17:38 UTC, mddilley reviewed
This all looks great, Chia! Go tags! 🏷️ I noticed that the tag deletes are not persisting after refresh so I'm going to take a quick look at how it works for subcomponents because everything in the code looks in order to me.

2023-05-18 17:52 UTC, mddilley commented on moped-editor/src/queries/components.js
>        where: { project_component_id: { _eq: $projectComponentId } }
Just realized what was going on here. This update mutation is first clearing all of the subcomponents by switching any `moped_proj_components_subcomponents` associated with the current component by switch them all to `is_deleted = true`. After that update, we insert the subcomponents chosen in the form, and, if there is a conflict, we update `is_deleted = true` to `is_deleted = false`.  So, the same update for tags is needed here to match up with what happens to subcomponents.

That took me a second to figure out again so let me know if that makes sense. More comments around this with wording from other people than me would make this clearer in the future.

2023-05-18 20:58 UTC, mddilley commented on moped-editor/src/queries/components.js
>        where: { project_component_id: { _eq: $projectComponentId } }
I think that your comment is much clearer! Thanks for updating it. 🙏

2023-05-18 21:09 UTC, mddilley approved these changes
🚢 ✨✨✨

2023-05-18 22:22 UTC, tillyw approved these changes

2023-05-19 20:39 UTC, frankhereford approved these changes
![flawlessly](https://github.com/cityofaustin/atd-moped/assets/3653206/87300a08-ee25-499a-9f18-db6eeb23d454)

🚀🚀🚀

2023-05-19 20:41 UTC, merged