Adds ability to copy user email addresses from staff list
cityofaustin/atd-moped pull request #1110
Opened 2023-08-23 15:37 UTC by johnclary

## Associated issues

## Testing
**URL to test:** 

**Steps to test:**

---
#### Ship list
- [ ] Code reviewed 
- [ ] Product manager approved
- [ ] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable

2023-08-23 16:25 UTC, johnclary commented on moped-editor/src/views/staff/EditStaffView.js
> +      note,
this fixes a bug i introduced [here](https://github.com/cityofaustin/atd-moped/pull/1096). it is not currently possible to edit these two user fields in Moped unless the user a non-login user :/

2023-08-23 19:02 UTC, chiaberry commented on moped-editor/src/views/staff/StaffListViewCustomComponents.js
> +    <div>
dunno if you want to give all users the ability to download the emails or only admins. i guess limiting who can see the button would just make the staff view "cleaner"

2023-08-23 19:03 UTC, chiaberry approved these changes
copied email addresses!

2023-08-23 19:20 UTC, mddilley approved these changes
Tested this out on the preview, and I like the UI flow! All the expected emails copied to my clipboard ✅ 🚢

2023-08-23 19:20 UTC, mddilley commented on moped-editor/src/views/staff/StaffListViewCustomComponents.js
> +    return () => clearTimeout(timeout);
love seeing a useEffect with cleanup - don't get to do this often 💯

2023-08-28 16:49 UTC, roseeichelmann requested changes
When i click on the copy buttons nothing is copied to my clipboard and i get the error "ReferenceError: ClipboardItem is not defined". I am testing on Firefox :0

[simplescreenrecorder-2023-08-28_11.45.17.webm](https://github.com/cityofaustin/atd-moped/assets/67130963/993adde0-4e03-412f-8b31-52ee3c1af88e)

2023-08-28 16:52 UTC, chiaberry commented
wont work on firefox :( https://developer.mozilla.org/en-US/docs/Web/API/ClipboardItem#browser_compatibility

2023-08-30 14:48 UTC, johnclary commented
i have re-requested review from all after making a few tweaks to the button labels to make the behavior more clear. i think it's fine to leave this button visible to all users 😅

2023-08-30 14:49 UTC, johnclary commented on moped-editor/src/views/staff/StaffListViewCustomComponents.js
> +  user.email.indexOf("+") < 0;
this excludes our test accounts e.g. "transportation.data+mopedadmin@austintexas.gov"

2023-08-30 14:54 UTC, chiaberry approved these changes
the menu and buttons are more clear this way, i like it

2023-08-30 15:39 UTC, roseeichelmann approved these changes
yay, works on firefox now! and i also like the updates to the buttons :ship:

2023-08-30 15:44 UTC, johnclary commented
thank you!!!

2023-08-30 15:44 UTC, merged

2023-08-30 15:45 UTC, mddilley approved these changes
Didn't retest the UI thoroughly but tested and reviewed the new commits, and this looks great! 🙏

2023-08-30 15:53 UTC, johnclary commented
thakns @mddilley for taking another look as well!