Add parent project names and subprojects to Project List View
cityofaustin/atd-moped pull request #1134
Opened 2023-09-18 21:36 UTC by chiaberry

## Associated issues

## Testing
**URL to test:** 

**Steps to test:**

---
#### Ship list
- [ ] Code reviewed 
- [ ] Product manager approved
- [ ] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable

2023-09-18 23:35 UTC, johnclary requested changes
Looks great—this will be a nic lil improvement! I have asked for minor changes.

🙌

2023-09-18 23:35 UTC, johnclary commented on moped-editor/src/views/projects/projectsListView/ProjectsListViewTable.js
> +      hidden: hiddenColumns["parent_project_id"],
would you make both of these new columns hidden by default? would you also make these columns hidden by default as well?

```
construction_start_date
completion_end_date
project_tags
```

2023-09-18 23:35 UTC, johnclary commented on moped-editor/src/views/projects/projectsListView/ProjectsListViewTable.js
> +              ? btoa(JSON.stringify(filters))
TIL [`btoa`](https://developer.mozilla.org/en-US/docs/Web/API/btoa)!

it looks like every cell in the table is using the same value for this link state. if you assigned this value outside the `columns` declaration you might see a speedup with rendering.

```jsx
# earlier
const linkStateFilters =  Object.keys(filters).length ? btoa(JSON.stringify(filters)) : false;


# inside the columns render definition
<RouterLink
          to={`/moped/projects/${entry.parent_project_id}`}
          state={{ filters: linkStateFilters }}>
```

2023-09-19 12:53 UTC, johnclary approved these changes
🙏 🚢 🚢 🚢 🚢

2023-09-19 17:58 UTC, johnclary commented
thanks @chiaberry!

2023-09-20 17:09 UTC, mddilley approved these changes
Tested this locally, and it is great to have this info in the list view. The migrations work up and down as well. Good to go! 🚢 🚀

2023-09-20 18:38 UTC, merged