disable write permissions primary keys
cityofaustin/atd-moped pull request #1230
Opened 2023-12-27 00:15 UTC by tillyw

## Associated issues

## Testing
**URL to test:** 

**Steps to test:**

---
#### Ship list
- [ ] Code reviewed 
- [ ] Product manager approved
- [ ] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable

2023-12-27 17:27 UTC, johnclary approved these changes
Wow, it's huge relief to have these permissions tightened up! I ran through a few test cases locally with admin and editor permissions and all seems to be working normally. 

Thank you!!!!!  🙌 🚢 🚢 🚢

2023-12-27 18:15 UTC, roseeichelmann approved these changes
looks good to me! its great this is getting addressed, thanks tilly!

2023-12-27 23:39 UTC, mddilley requested changes
This looks awesome, Tilly! So much improvement. ✨ I think that I found one last primary key permission to revoke - insert and update of `project_component_id ` in the `moped_proj_components` table. If I missed something different about that one, I'll turn this right into a ✅.

2023-12-27 23:41 UTC, mddilley commented on moped-database/metadata/tables.yaml
> -          - project_id
+1 - the ones without `id` for the primary key are tricky!

2023-12-28 22:31 UTC, tillyw commented
> This looks awesome, Tilly! So much improvement. ✨ I think that I found one last primary key permission to revoke - insert and update of `project_component_id ` in the `moped_proj_components` table. If I missed something different about that one, I'll turn this right into a ✅.

that one slipped past me - thanks for catching it! i've pushed a new commit that delete the pkey `update` and `insert` permissions for `moped_proj_components`!

2023-12-28 23:21 UTC, mddilley approved these changes
Looks amazing! We can rest easy knowing that these columns are locked down now 🔒✨

2023-12-29 18:03 UTC, chiaberry approved these changes
ditto to everyone else! we can sleep soundly now

2024-01-02 21:16 UTC, merged