Help menu icons are not hyperlinked
cityofaustin/atd-moped pull request #1244
Opened 2024-01-17 20:56 UTC by roseeichelmann

## Associated issues
Closes https://github.com/cityofaustin/atd-data-tech/issues/15036

## Testing
**URL to test:** 

**Steps to test:**
1. Click on the help menu navbar, test clicking on the icons of each menu item. Clicking on the icon should redirect you. Also clicking on the very edge of the menu item should redirect you.
2. Now test on mobile. Before this update clicking on the very edge of the menu item wouldn't redirect you, now it should.

---
#### Ship list
- [ ] Code reviewed 
- [ ] Product manager approved
- [ ] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable

2024-01-17 20:57 UTC, roseeichelmann commented on moped-editor/src/layouts/DashboardLayout/NavBar/DropdownMenu.js
> +            <ListItemIcon>{arcGISLink.Icon}</ListItemIcon>
just moving the Link component outside of the MenuItem

2024-01-17 21:25 UTC, johnclary requested changes
Works beautifully! there's just a lil console error to squash 🙏

2024-01-17 21:25 UTC, johnclary commented on moped-editor/src/layouts/DashboardLayout/NavBar/DropdownMenu.js
> -              <MenuItem key={item.link} onClick={handleDropdownClose}>
it looks like you need to move the `key` prop up to the `Link` component. i'm getting the warning:

```
DropdownMenu.js:116 Warning: Each child in a list should have a unique "key" prop.
```

2024-01-17 22:54 UTC, mddilley approved these changes
So rad! Tested on the preview, and I'm redirected no matter where I click in the menu items. Thanks for making them more forgiving! 🙌 🚢

2024-01-17 23:01 UTC, chiaberry approved these changes
approval assuming you will squash that console error
and then we can click wherever we want on the menu!

2024-01-18 17:14 UTC, johnclary approved these changes
🚢 🚢 🚢 🚢 🚢 🚢 ✨

2024-01-18 18:48 UTC, merged