Add an activity event to track when when the Dashboard page loads
cityofaustin/atd-moped pull request #1252
Opened 2024-01-24 17:42 UTC by johnclary

## Associated issues

## Testing
**URL to test:** 

**Steps to test:**

---
#### Ship list
- [ ] Code reviewed 
- [ ] Product manager approved
- [ ] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable

2024-01-26 00:10 UTC, mddilley requested changes
Love seeing the tracker grow so easily to handle new events!! 🚀 🙌 The down migration doesn't work as is, but, imo, we move forward and never go back! 🏎️💨💨 Probably need a comment that there is no going back? Not sure how we want to handle that.

2024-01-26 00:10 UTC, mddilley commented on moped-database/migrations/1706117943942_add_dashboard_load_event/up.sql
> +    ADD CONSTRAINT moped_user_events_event_name_check CHECK (event_name in('app_load', 'dashboard_load'));
✨

2024-01-26 17:22 UTC, chiaberry approved these changes
I'm looking forward to finding out who uses the dashboard page and how often

2024-01-26 17:30 UTC, mddilley approved these changes
Ready to go and to start collecting new events. 👀 🙌

2024-01-26 17:30 UTC, mddilley commented on moped-database/migrations/1706117943942_add_dashboard_load_event/down.sql
> +DELETE FROM moped_user_events where event_name = 'dashboard_load';
Cool, that makes sense to me! 🙏

2024-01-29 15:55 UTC, johnclary commented
🍿

2024-01-29 15:55 UTC, merged