replace moped_proj_notes rest connectors with db triggers
cityofaustin/atd-moped pull request #1280
Opened 2024-02-16 00:16 UTC by tillyw

## Associated issues
fixes https://github.com/cityofaustin/atd-data-tech/issues/15489

## Testing
**URL to test:** 

**Steps to test:**

---
#### Ship list
- [ ] Code reviewed 
- [ ] Product manager approved
- [ ] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable

2024-02-16 00:19 UTC, tillyw commented on moped-database/metadata/tables.yaml
> -          updated_by_user_id: x-hasura-user-db-id
this is just moving stuff around you can ignore this

2024-02-26 16:57 UTC, mddilley approved these changes
I'm seeing the updated behavior for all inserts, edits, and deletes of notes and status updates. I also see the parent project timestamp updating. Hooray! 🙌 🚢

2024-02-26 16:57 UTC, mddilley commented on moped-editor/src/views/projects/projectView/ProjectPhase/helpers.js
> -          added_by_user_id: noteData.user_id,
thanks for catching this update in the phase form! 🙏

2024-02-27 15:52 UTC, chiaberry approved these changes
ran through the test steps, was going to test if edits by other users worked as expected, then i remembered you cant edit other peoples notes
🚢

2024-02-27 15:55 UTC, chiaberry commented
> Unrelated to the changes in this PR, but I noticed that, when creating a new note, the `updated_at` timestamp is slightly ahead of the `created_at` timestamp. I expected them to be the same, and I think we could make a small adjustment to `public.update_self_and_project_updated_audit_fields()` to use the value of `created_at` of the new record instead of calling `NOW()`.
> 
> What do you think @chiaberry? Might not be as big of deal as I'm thinking.

Thats a good question @mddilley , I did not notice they were slightly out of sync, and that the updated_at happens BEFORE insert or update, so the updated at is before the created at time. 

On one hand it bothers me because it feels illogical to have something be updated at before its created, but I am trying to come up with scenarios where we would regret these discrepancies, and I cant come up with one. Would we be able to make an adjustment to the function to be able to pass the created_at before insert? I am thinking we cant get the created at time until after its been created and this happens before....

2024-02-27 16:26 UTC, johnclary commented
good catch @mddilley i think we should patch that function to use the `created_at` timestamp. you can use the `TG_OP` context variable to see if we're handling an insert vs update 😅

2024-02-27 16:43 UTC, chiaberry requested changes
The dashboard query is referencing created_at, I get an apollo error when i navigate to the Dashboard

https://github.com/cityofaustin/atd-moped/blob/main/moped-editor/src/queries/dashboard.js#L30

2024-02-28 23:09 UTC, tillyw commented
> The dashboard query is referencing created_at, I get an apollo error when i navigate to the Dashboard
> 
> https://github.com/cityofaustin/atd-moped/blob/main/moped-editor/src/queries/dashboard.js#L30

thanks for catching this! i forgot about the dashboard >.< fixed!

2024-02-29 15:14 UTC, chiaberry approved these changes
thanks for fixing the dashboard query, the ✅  is back

2024-02-29 15:34 UTC, chiaberry commented
going to merge so we can start testing

2024-02-29 15:34 UTC, merged