Testing the pro version
cityofaustin/atd-moped pull request #1303
Opened 2024-03-25 21:24 UTC by chiaberry

## Associated issues

## Testing
**URL to test:** 

**Steps to test:**

---
#### Ship list
- [ ] Code reviewed 
- [ ] Product manager approved
- [ ] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable

2024-04-22 21:13 UTC, chiaberry commented on moped-editor/src/views/projects/projectsListView/ProjectsListViewQueryConf.js
> +    rowsPerPageOptions: [100, 250, 1000],
setting this back to what we used to have

2024-04-24 16:06 UTC, mddilley requested changes
All this looks great, Chia! So cool to the pinning in action and the pagination limit uncapped. I also tested the license locally, and it works perfectly. MUG is gonna love this upgrade! 🙌

I noticed one small regression - the density toggle isn't having an effect on the table rows anymore.

2024-04-24 16:06 UTC, mddilley commented on moped-editor/src/views/projects/projectsListView/ProjectsListViewTable.js
You had mentioned the grey background in dev sync when pinning the columns to the left or right, and I saw that the header row also has it. I do think that a white background [like in their demo](https://mui.com/x/react-data-grid/demo/) looks nicer and also a lot like what we used to have with the frozen project ID column. 

I wonder if that color is inherited from something in our theme file because it is behaving like the default? Not sure.

<img width="354" alt="Screenshot 2024-04-24 at 10 50 12 AM" src="https://github.com/cityofaustin/atd-moped/assets/37249039/70e63ae2-defc-4417-a965-cf64892eab1e">

2024-04-24 17:12 UTC, chiaberry commented on moped-editor/src/views/projects/projectsListView/ProjectsListViewTable.js
oh good call about the demo -- ill look for how come this is gray when the demo isnt

2024-04-24 17:14 UTC, chiaberry commented
I'll remove the density toggle, I dont think anyone wants it anyway

2024-04-25 05:14 UTC, amenity commented
Sweet! All works great for me. 

Question, though: I think the grey background is actually kinda noisy, and the reduced contrast reduces legibility, too. What do you think about tweaking these styles so the table colors stay the same?  
- `DataGrid-containerBackground: #fff`
- `DataGrid-pinnedBackground: #fff`

Current Moped - sans Pro:
<img width="1489" alt="Screenshot 2024-04-25 at 12 14 02 AM" src="https://github.com/cityofaustin/atd-moped/assets/1463708/bd7e32a5-e9e4-4115-b157-566ce7b4e0f7">


DataGridPro default:
<img width="1486" alt="Data Grid Pro default" src="https://github.com/cityofaustin/atd-moped/assets/1463708/28f91a74-7dfd-4b5b-bc48-ec417d77f691">

Proposed: 
<img width="1486" alt="Proposed" src="https://github.com/cityofaustin/atd-moped/assets/1463708/53328a8e-0b87-449d-b676-542532dc446b">

2024-04-25 20:09 UTC, chiaberry commented on moped-editor/src/views/projects/projectsListView/ProjectsListViewTable.js
its from our theme! https://mui.com/x/react-data-grid/style/#theme-header-and-pinned-sections
But when I try to follow these instructions, it wont work. ill keep tinkering

2024-04-25 23:24 UTC, amenity approved these changes
Perfection, thanks! ✨ I really appreciate all your research (for a lonnng time now) into how-do-we-progress w/ MUI, @chiaberry 🕵🏻‍♀️ 🙏🏻

2024-04-26 13:22 UTC, mddilley approved these changes
Looks awesome with the updates! 🚢 🙌

2024-04-26 16:24 UTC, roseeichelmann approved these changes
such a cool feature with the pinning columns!! looks great :)

2024-04-26 16:36 UTC, merged