[Bug] Error happens when not completely removing an advanced search filter
cityofaustin/atd-moped pull request #1335
Opened 2024-05-01 22:43 UTC by roseeichelmann

## Associated issues

## Testing
**URL to test:** 

**Steps to test:**

---
#### Ship list
- [ ] Code reviewed 
- [ ] Product manager approved
- [ ] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable

2024-05-08 19:47 UTC, roseeichelmann commented on moped-editor/src/components/GridTable/Filters.js
> +  );
this keeps advanced search filter changes from persisting when the user exits out without applying. now when this component renders it is pulling from the URL search params initially

2024-05-08 19:48 UTC, roseeichelmann commented on moped-editor/src/components/GridTable/Filters.js
> -    } else if (remainingFiltersCount === 1) {
we shouldnt be making any changes to the URL search params when a filter is deleted. the URL should only be updated once the Apply button is clicked.

2024-05-08 21:31 UTC, roseeichelmann commented on moped-editor/src/components/GridTable/Filters.js
> -  const handleResetFilters = useCallback(() => {
i dont think this needs a `useCallback` anymore, previous this function was called within a `useEffect` but now its not

2024-05-08 21:52 UTC, roseeichelmann commented on moped-editor/src/components/GridTable/Filters.js
> +  setSearchParams,
im not sure exactly why but sharing these with the Search parent component and passing them down from there fixed some issues with the URL search params not clearing on Reset button click

2024-05-08 22:00 UTC, roseeichelmann commented on moped-editor/src/components/GridTable/Filters.js
> +      });
here, after the user clicks apply, is where we should clear the URL search params if the filters were deleted

2024-05-09 17:15 UTC, mddilley requested changes
This is amazing, Rose! This feels so much better and made me realize how confusing some of the existing behavior can be. I stepped through a bunch of filter combos (simple, advanced, and/or) locally, and all of this looks ✨. I added a comment about a small regression that I think should be fixed.

2024-05-09 17:15 UTC, mddilley commented on moped-editor/src/components/GridTable/helpers.js
> +  advancedSearchFilterParamName
Small thing that jumped out at me with this `advancedSearchFilterParamName` param is that I kept mixing this up with the specific const that stores the `filters` string used in the url. Maybe naming it something more general could work or maybe it is just my brain 🙃

I also realize that it is only used for that specific search param so maybe it doesn't really matter at all!

2024-05-09 19:07 UTC, chiaberry commented
I agree with @mddilley that we should keep the functionality where a blank filter is automatically included when someone opens the advanced filters. 

I tested with different filters and followed your test steps and I couldnt break it! After that regression is fixed, ill 👍🏼

2024-05-09 20:20 UTC, frankhereford approved these changes
Thank you Rose. Nothing simple about this code at all, at least not to me. I think this might be a bit bigger than the snackoo label it had!

I've read through your code, and nothing is jumping out at me. Mike's catch on suppressing the 'No filters applied' is very sharp, thank you Mike! Testing out the functionality based on your instructions and poking around with it -- 💯 

Thanks again 🚢 🚢🚢

2024-05-09 20:20 UTC, frankhereford commented on moped-editor/src/components/GridTable/Filters.js
> + * @param {Function} setSearchParams - Function to set the URL search params
Thanks for being diligent and keeping these up to date. I find them easy to miss.

2024-05-09 21:09 UTC, tillyw approved these changes
tested locally and tried a whole variety of states and everything worked as expected! this is a huge improvement and makes a lot more sense to me as a user. i agree it would be nice to have a blank filter appear in the initial state (which would mirror the state you get when you click the 'reset' button). thanks for working through all these different possible states!

2024-05-09 21:53 UTC, roseeichelmann commented
@mddilley thanks for catching that regression, you do have a really good eye! just pushed up the fix

2024-05-09 21:57 UTC, amenity approved these changes
Really nice! Thanks, @roseeichelmann ✨ 🚢

2024-05-09 23:01 UTC, mddilley approved these changes
Amazing! All of this works so well - thanks! 🚢 🙌 🚢

2024-05-10 13:48 UTC, chiaberry approved these changes
🚢

2024-05-10 14:43 UTC, merged