Update more advanced search fields to use lookups with contains operator
cityofaustin/atd-moped pull request #1406
Opened 2024-09-03 15:05 UTC by chiaberry

## Associated issues

## Testing
**URL to test:** 

**Steps to test:**

---
#### Ship list
- [ ] Code reviewed 
- [ ] Product manager approved
- [ ] Product manager checked [DB view dependencies](https://atd-dts.gitbook.io/moped-documentation/product-management/updating-the-arcgis-online-components-database-view)
- [ ] Product manager added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable

2024-09-04 17:21 UTC, chiaberry commented on moped-editor/src/views/projects/projectsListView/ProjectsListViewQueryConf.js
> - * @augments PROJECT_LIST_VIEW_FILTERS_CONFIG
it does not

2024-09-04 21:51 UTC, roseeichelmann commented on moped-editor/src/views/projects/projectsListView/ProjectsListViewFiltersConf.js
> +    defaultOperator: "string_equals_case_insensitive",
i think this needs to be updated to `string_contains_case_insensitive` to get the default contains setting

2024-09-04 22:05 UTC, roseeichelmann requested changes
Love the refinements we have been making to the advanced search recently! Type still needs to be updated to default to contains. Im also not seeing autocomplete options for Inspectors or Designers.Also confused about the free solo option - does that mean we should be able to search on those without actually clicking an option? Or what is the effect we see from that, i dont think im seeing it but maybe i dont know what im looking for

2024-09-04 22:22 UTC, mddilley commented on moped-editor/src/components/GridTable/Filters.js
> +                          showFreeSolo
i like Rose's comment about wanting more info about how this option is used. Moving this logic into a helper function could be helpful to doc and extend the logic in the future. I could see entering an arbitrary string helping with the `string_contains_not_case_insensitive` operator too.

2024-09-04 22:24 UTC, mddilley commented
@chiaberry I also ran into the issue that Rose described above. I'll hold off on review for now.

Also, thank you for tackling the config refactor!! It will be nice to get away from the array of fields shape that doesn't quite fit the way we handle the queries in the post-GraphQLAbstract code. 🙌

2024-09-04 23:16 UTC, chiaberry commented
I'm so sorry guys that I asked for review and hadnt pushed up my last commit 

Thanks for catching the default operator I missed updating @roseeichelmann , I am noticing now how the config is inconsistent with using that to define the default operator. I'll add that to the rest of the config entries. 

As for the fresolo option, let's talk about it tomorrow, I can pull it into a helper function but I am not sure how we could convey to users that that option is there....

2024-09-05 22:44 UTC, mddilley requested changes
This works great!!! 🙌 The config refactor is a total win all around too. I thought more about the freeSolo option, and I agree with you that we should hit the eject button on it again. Maybe the third time around it will stick. I will create an issue for it so we can find the best way to incorporate it.

2024-09-05 22:44 UTC, mddilley commented on moped-editor/src/views/projects/projectsListView/ProjectsListViewFiltersConf.js
> +      operators: ["string_contains_case_insensitive"],
Forgive me for going back on the issue requirements but could you add `string_equals_case_insensitive` and `string_does_not_equal_case_insensitive` back in for `type_name` and `project_partners`? No change to default operator. Today's dev sync discussion made me realize this is actually taking away valid searches like "a project with one type that is _____".

2024-09-06 15:51 UTC, mddilley commented on moped-editor/src/components/GridTable/helpers.js
> +      const fieldConfig = filtersConfig[fieldName];
https://github.com/cityofaustin/atd-data-tech/issues/18935

2024-09-06 15:52 UTC, mddilley commented on moped-editor/src/views/projects/projectsListView/ProjectsListViewFiltersConf.js
> +      operators: ["string_contains_case_insensitive"],
thanks for updating! 🙏

2024-09-06 21:52 UTC, mddilley approved these changes
I tested through the updated defaults, new lookups, filter chips, and the rest of the filters too. All looks great to me! Thanks for the extra refactoring too - glad the time finally came to address the shape of the filter config! 🚢 😎

2024-09-11 15:43 UTC, mddilley commented
@roseeichelmann thanks again for flagging how confusing the freeSolo option could be! I captured your feedback and discussion from dev sync last week in https://github.com/cityofaustin/atd-data-tech/issues/18934. Re-requesting your review since Chia is out this morning.

2024-09-11 22:20 UTC, tillyw approved these changes
tested and working great! thanks for making these improvement Chia!

potential future pr, but i noticed during testing if you select an option in a dropdown and then change the field value the option remains selected even if it is not part of the new field's dropdown selections. it might be nice to clear the option value when the field value is changed.

2024-09-12 04:36 UTC, roseeichelmann approved these changes
this looks and works great!! kicking the can on the free solo feature to another pr sounds good to me :ship:

2024-09-12 14:08 UTC, merged

2024-09-12 18:07 UTC, mddilley commented
@tillyw just caught your comment - i will create an issue for that because it is also confusing to me to carry over a value from one search field to another unrelated one! 🙏