Make school zone beacons from open dataset available to choose in components form
cityofaustin/atd-moped pull request #1409
Opened 2024-09-09 18:33 UTC by chiaberry

## Associated issues

## Testing
**URL to test:** 

**Steps to test:**

---
#### Ship list
- [ ] Code reviewed 
- [ ] Product manager approved
- [ ] Product manager checked [DB view dependencies](https://atd-dts.gitbook.io/moped-documentation/product-management/updating-the-arcgis-online-components-database-view)
- [ ] Product manager added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable

2024-09-18 18:07 UTC, johnclary requested changes
Wow—this looks great 🤩 

~I am running into one issue which occurs in a few different edit scenarios~

Update: i am no longer able to reproduce this bug 🙃 

This feature is looking awesome—you've done a great job working this into the existing code 🔥

2024-09-18 18:07 UTC, johnclary commented on moped-editor/src/views/projects/projectView/ProjectComponents/SchoolBeaconComponentAutocomplete.js
not 100% sure on this or how much we care, but it seams like the signal and school beacon autocompletes could be one component with diff props 👀

2024-09-18 18:28 UTC, mddilley commented on moped-database/migrations/1725983667950_add_beacons_asset_table/up.sql
> +    updated_at timestamptz NULL
good catch! yes, could you make that update @chiaberry? And, while you are at it, could you copypasta the comments that we have on these four audit fields in the other feature tables? thank you! 🙏 🙏

2024-09-18 18:51 UTC, chiaberry commented on moped-editor/src/views/projects/projectView/ProjectComponents/SchoolBeaconComponentAutocomplete.js
ill try it!!

2024-09-18 20:20 UTC, chiaberry commented on moped-editor/src/views/projects/projectView/ProjectComponents/ProjectComponentsListItem.js
>                  : "Map"
updated! thank you for the rewording

2024-09-18 20:59 UTC, mddilley reviewed
Unleashing some comments that I've been holding on to this afternoon. I'll keep reviewing! It is looking ✨!

2024-09-18 21:26 UTC, chiaberry commented on moped-database/migrations/1725983667950_add_beacons_asset_table/up.sql
> +    beacon_id text,
I cant believe I missed this, I am requesting the field in the socrata endpoint, but not saving it in the database. 

I am using the beacon_id in order to create the unique option label, but the school_zone_beacon_id is what I should use as the layers primary key column

2024-09-18 21:55 UTC, chiaberry commented on moped-editor/src/utils/signalComponentHelpers.js
> +      location_name: `${schoolBeacon.properties.zone_name} ${schoolBeacon.properties.beacon_name}`,
I am going to make this change, but now I am wondering if we need the zone name or beacon name from knack at all....

2024-09-18 21:56 UTC, chiaberry commented on moped-editor/src/utils/signalComponentHelpers.js
> +      location_name: `${schoolBeacon.properties.zone_name} ${schoolBeacon.properties.beacon_name}`,
never mind! we still need them in the options formatter for the auto complete

2024-09-23 23:33 UTC, mddilley requested changes
This looks ready to go to me! I mentioned you in a couple comments for some last small changes. One was from John's review. I think this is ready to go after that and when the next two issues are complete. 🙌

2024-09-23 23:33 UTC, mddilley commented on moped-editor/src/views/projects/projectView/ProjectComponents/KnackComponentAutocomplete.js
> +        id="knack-component-autocomplete-id"
@chiaberry Could you remove the `-id` part of this id string? This is causing the 1PW extension to want to autofill on it for some reason. 🤷 This is an existing issue in prod for this autocomplete signals so not something you introduced.

<img width="594" alt="Screenshot 2024-09-23 at 6 08 01 PM" src="https://github.com/user-attachments/assets/fa34cac8-acc0-4bf8-b6d3-9f5c638603b1">

2024-09-23 23:33 UTC, mddilley commented on moped-editor/src/views/projects/projectView/ProjectComponents/utils/makeComponentData.js
> +      // if there was a beacon that was switched to signal, we need to clear that beacon
This is also a good reminder of how we handle all of the update scenarios that can happen through the form!

2024-09-23 23:33 UTC, mddilley commented on moped-database/migrations/1725983667950_add_beacons_asset_table/up.sql
> +    updated_at timestamptz NULL
@chiaberry could you add the comments on the audit fields `created_at`, `created_by_user_id`, `updated_by_user_id`,`updated_at`? The same ones that we have on the other feature tables. Thanks for updating the update_at default! 🙏

2024-09-23 23:33 UTC, mddilley commented on moped-database/migrations/1725983667950_add_beacons_asset_table/up.sql
> +    beacon_name text,
thanks for updating, Chia! 🙏

2024-09-24 16:54 UTC, chiaberry commented on moped-editor/src/views/projects/projectView/ProjectComponents/CreateComponentModal.js
> +    const isSavingSignalFeature = Boolean(formData.signal || formData.schoolBeacon);
its a good detail.

2024-09-24 19:17 UTC, roseeichelmann commented
I'm getting a bit confused by `Signal - School Zone Beacon`, `Flashing Zone Beacon -` , and `Signal - PHBs`. In your instructions when you say test editing a Beacon, do you mean a `Signal - School Zone Beacon`? And what do you mean by test changing it to a signal? Do you want us to update it to like `Signal - PHB`? And vice versa? Or do i have that totally wrong. Im not super familiar with the different component terminology so im getting so confused by the overlapping names

2024-09-24 19:26 UTC, chiaberry commented
@roseeichelmann yeah sorry, the nomenclature is pretty confusing and I totally forgot about the Flashing Zone Beacon. 

School Zone Beacon is what I mean when I say "Test the beacons" (in the future its going to be renamed to Beacon -School Zone so hopefully that helps https://github.com/cityofaustin/atd-data-tech/issues/19040)

and the change to a signal, change it to either a Signal PHB or Signal Traffic

2024-09-25 00:04 UTC, mddilley commented on moped-database/migrations/1725983667950_add_beacons_asset_table/up.sql
> +    updated_at timestamptz NULL
looks great! thank you Chia!

2024-09-25 00:13 UTC, mddilley commented on moped-editor/src/views/projects/projectView/ProjectComponents/KnackComponentAutocomplete.js
> +        id="knack-component-autocomplete-id"
yay! thank you for squeezing this in. Such a nice detail to tie up 🙌

2024-09-25 00:16 UTC, mddilley approved these changes
I tested this again through all the ways of creating a school zone beacon, and it all looks great to me! Putting this approval on here so it will be ready for when the time comes to merge with the other branches. 🙌

2024-09-26 14:48 UTC, johnclary approved these changes
i tested this a bunch more—it works great. thanks for making those changes. this is exciting! 🚢 🚢 🚢

2024-09-26 18:17 UTC, merged