Moar `<FormattedDateString>`
cityofaustin/atd-moped pull request #1450
Opened 2024-10-09 20:46 UTC by mateoclarke

## Associated issues

Closes https://github.com/cityofaustin/atd-data-tech/issues/19044

## Testing

**URL to test:** 

_Since this is a PR off a branch from main ([chia's PR](https://github.com/cityofaustin/atd-moped/pull/1438)), we'll have to test this locally until that upstream PR branch is merged to `main`_

**Steps to test:**

1. Check the **Modified** column and the date format for each row on the project list
  - https://localhost:3000/moped/projects
2. Check the **Date uploaded** column in the project files tab table for the expected date formatting
  - https://localhost:3000/moped/projects/227?tab=files
3. Check the 3rd column in the Project Activity log for the expected date formatting
  - ex: https://localhost:3000/moped/projects/227?tab=activity_log

---
#### Ship list
- [x] Code reviewed 
- [x] Product manager approved
- [x] Product manager checked [DB view dependencies](https://atd-dts.gitbook.io/moped-documentation/product-management/updating-the-arcgis-online-components-database-view)
- [x] Product manager added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable

2024-10-09 23:33 UTC, mddilley requested changes
<img src="https://media0.giphy.com/media/Z3pez2XOAb11naBDbh/giphy.gif"/>

I requested two tiny changes - this looks amazing! Thank you for spreading this component to more places! 🎉

2024-10-09 23:33 UTC, mddilley commented on moped-editor/src/views/projects/projectsListView/helpers.js
>          width: COLUMN_WIDTHS.small,
this wasn't in the issue, but i'm now noticing that we could update this to `COLUMN_WIDTHS.medium` to keep the secondary part of the timestamp from wrapping in cell when its default width loads. Could you make that change? Thanks!

2024-10-09 23:33 UTC, mddilley commented on moped-editor/src/views/projects/projectsListView/helpers.js
> +import { formatDateType, FormattedDateString, formatTimeStampTZType } from "src/utils/dateAndTime";
I'm seeing a compile warning that `formatTimeStampTZType` isn't being used. could you remove? 🙏

2024-10-10 14:24 UTC, chiaberry commented
I merged the upstream branch and switched the base branch to main, hoping it would trigger a netlify deploy but alas no

2024-10-10 14:57 UTC, mddilley approved these changes
Love seeing this component in more places - thanks! ⏳ 🙌 🚢

2024-10-10 15:28 UTC, merged