Project Phases enhancements
cityofaustin/atd-moped pull request #207
Opened 2021-02-09 07:00 UTC by mateoclarke

https://github.com/cityofaustin/atd-data-tech/issues/5210

### - Updates True/False label text to Yes/No with “switch” toggle component in edit mode.

**read-mode, Yes/No labels**
![Screen Shot 2021-02-09 at 12 59 07 AM](https://user-images.githubusercontent.com/5697474/107327081-1c630700-6a72-11eb-87aa-ef263e99753b.jpg)

**edit-mode, Material UI "Switch" component**
![Screen Shot 2021-02-09 at 12 59 12 AM](https://user-images.githubusercontent.com/5697474/107327069-1705bc80-6a72-11eb-816d-29705854d59a.jpg)

2021-02-10 18:52 UTC, zappfyllc requested changes
@mateoclarke Looking great! Quick comments:

- You interpreted correctly. I think sorting by newest phase, aka descending from phase_start is definitely a good default behavior. If we need to change it in the future, we can.
- I love the Material UI Switch: let's remove the "Yes/No" labels on the sides of the switch component and let the switch should speak for itself. If users are confused, we'll figure it out via testing but I think this would look the best.

Looks great, Mateo!

2021-03-08 18:28 UTC, sergiogcx commented on moped-editor/src/views/projects/projectView/ProjectTimeline.js
> +
I love seeing these! 👍

2021-03-08 18:29 UTC, sergiogcx commented on moped-editor/src/views/projects/projectView/ProjectTimeline.js
> +                        />
Neat!

2021-03-08 18:29 UTC, sergiogcx approved these changes

2021-03-08 19:01 UTC, amenity approved these changes
Sorry - spastic button clicking earlier. 🤦🏻  This looks super, @mateoclarke!

2021-03-08 19:14 UTC, amenity commented
Will applying that 'color="primary"` prop take care of #5424?

2021-03-08 19:31 UTC, mateoclarke commented
> Will adding [that `color="primary"` prop](https://github.com/cityofaustin/atd-moped/pull/207/commits/7b8dfbfee902b66bd5d344a36f56d3b81b080db4) take care of #5424?

Yeah I think that would do it!

2021-03-08 19:31 UTC, merged