Implement design refinements to "Staff" page #6674
cityofaustin/atd-moped pull request #380
Opened 2021-07-30 18:48 UTC by sergiogcx

Closes https://github.com/cityofaustin/atd-data-tech/issues/6674

** UI Change only, see live demo:

Changes to the staff list:
- [x] Remove pagination (show all records)
- [x] Remove "Date Added" and "Cognito user ID"*
- [x] Increase "Workgroup" column width so that it doesn't wrap at full/desktop width.
- [x] Add column "Role" (viewer, editor, or admin)
- [x] Default sort alphabetical by first name

2021-07-30 18:49 UTC, sergiogcx commented on moped-editor/src/views/staff/StaffListViewQueryConf.js
> +  },
Default sort is by first name ascending

2021-07-30 18:49 UTC, sergiogcx commented on moped-editor/src/views/staff/StaffListViewQueryConf.js
> +      width: "10%",
Shows role, removes the "moped-*" string

2021-07-30 18:50 UTC, sergiogcx commented on moped-editor/src/components/GridTable/GridTable.js
> +                )}
The showPagination setting was provided but not implemented, so I just added a few extra lines of code to take care of that. Whenever showPagination is false, it disables pagination entirely and shows everything in a single page.

2021-08-01 20:39 UTC, chiaberry approved these changes

2021-08-03 00:41 UTC, amenity requested changes
@sergiogcx - thanks, this looks super. 

I think a few tweaks to column width would make the best use of space:

- First name - 15%
- Last name - 15%
- Email - 20%
- Title - 20%
- Workgroup - 20%
- Role - 10%

2021-08-03 02:36 UTC, mateoclarke approved these changes
🚢

2021-08-03 15:05 UTC, sergiogcx commented
@amenity I've updated the column widths, lmk if there are any more refinements you would like to include.

2021-08-03 21:49 UTC, amenity approved these changes
LSTM! ✨

2021-08-03 22:00 UTC, merged