Implement ability to toggle and edit components from full page map #6845
cityofaustin/atd-moped pull request #387
Opened 2021-08-05 19:06 UTC by sergiogcx

Closes https://github.com/cityofaustin/atd-data-tech/issues/6845

** Front-end changes only, test on Netlify

2021-08-05 19:52 UTC, sergiogcx commented on moped-editor/src/views/projects/projectView/ProjectComponents.js
> +            </Button>
Basically we get rid of the Table family of components for the List family of components.

2021-08-05 19:53 UTC, sergiogcx commented on moped-editor/src/views/projects/projectView/ProjectComponents.js
> +              </ClickAwayListener>
This is where we pass the List components (including the ClickAwayListener) directly as children of the map component.

2021-08-05 19:54 UTC, sergiogcx commented on moped-editor/src/views/projects/projectView/ProjectComponentsMapView.js
> +}));
We incorporate the same styles from the component editor (copy-pasta)

2021-08-05 19:55 UTC, sergiogcx commented on moped-editor/src/views/projects/projectView/ProjectComponentsMapView.js
> +
The filtering works a little different than the map, this is because we do not make use of interactive layers.

2021-08-09 23:53 UTC, patrickm02L requested changes
I like how the Components window stops right before it hits the mapbox logo and turns into window that scrolls. Can you copy this format when you are in 'Add New'/'Edit' mode for the components to create continuity between the two windows?

The arrows on the right side of the components that take you to edit are reading BIG, can you reduce them by 25%, so that they align with the height of the text on one line? 

![Screen Shot 2021-08-09 at 6 24 23 PM](https://user-images.githubusercontent.com/5566727/128786895-332ea8ca-fa5f-4b05-959a-a68774b56c72.png)
![Screen Shot 2021-08-09 at 6 23 57 PM](https://user-images.githubusercontent.com/5566727/128786906-82b266c5-debc-4e35-ab2b-2128a8cac3e9.png)

2021-08-11 23:41 UTC, patrickm02L approved these changes
Everything works like a dream! SHIP IT!

2021-08-12 03:32 UTC, mateoclarke approved these changes
🚢

2021-08-12 03:32 UTC, mateoclarke commented on moped-editor/src/views/projects/projectView/ProjectComponents.js
> +                          secondary={
this is a lot of logic to put within a prop. I wonder if the code would be neater if you could define this output as a variable and move into a separate function. Could also allow for more comment explaining the intention.

2021-08-12 13:54 UTC, merged