Add project types to signal project dashboard and project summary views
cityofaustin/atd-moped pull request #483
Opened 2021-11-30 22:59 UTC by chiaberry

## Associated issues
https://github.com/cityofaustin/atd-data-tech/issues/7713

## Testing
**URL to test:** 
Need to deploy to moped-test to test or run locally, there are db changes. 

**Steps to test:**

---
#### Ship list
- [ ] Code reviewed 
- [ ] Product manager approved
- [ ] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#gid=776973707)

2021-12-01 17:02 UTC, sergiogcx commented on moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryProjectTypes.js
> +  );
[Looking back](https://github.com/cityofaustin/atd-moped/pull/450/files#diff-b26f3e28654dd086f13a0473547d1ae187d5222c3156708a18623633ca34a270R39-R45) I wonder if I should have used a `.forEach` and something like `typeList[n.type_id] = n.type_name`.  It looks great, though! 👍  It works as expected.

2021-12-01 17:03 UTC, sergiogcx commented on moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryProjectTypes.js
> +    const typeIdsToInsert = newTypesList.filter(t => !oldTypesList.includes(t));
Another throwback for me, maybe there is a way to improve the O(n*n) performance, but the list is so small its kind of irrelevant. 👍  Feel free to challenge these as you code.

2021-12-01 17:04 UTC, sergiogcx approved these changes
Works great! 🚢  🚀  📦

2021-12-02 21:45 UTC, frankhereford approved these changes
I have gone over the code, but not in super detail. I have tested the intended functionality based on your (really helpful) PR initial comment, and I find everything to work exactly as one would expect. 💯 

I think the way this UI is designed and coded up feels really good to use -- I think this is great work.

2021-12-03 00:26 UTC, amenity requested changes
This looks and works great! I guess that you're thinking forward to future use cases, @zappfyllc, in using a multi-select? Just noticing that all the projects currently in Knack only have one type. 

My only request, just added to [docs](https://atd-dts.gitbook.io/moped/dev-guides/design-system/component-styles#select-fields), is that we use our primary color for the boxes instead of the secondary.

2021-12-03 14:46 UTC, chiaberry commented
@amenity I will make that change. I'm going to go ahead and update the project partner checkboxes to also be blue so they both match.

2021-12-03 22:46 UTC, amenity approved these changes
LSTM✨

2021-12-03 23:17 UTC, mateoclarke approved these changes
🚢 💨 ✨

2021-12-06 15:35 UTC, zappfyllc approved these changes
Looks and works great @chiaberry!

2021-12-06 16:49 UTC, merged