Add eCAPRIS field to "Funding" tab and adjust required fields #8079
cityofaustin/atd-moped pull request #523
Opened 2022-01-13 17:28 UTC by sergiogcx

## Associated issues

Closes https://github.com/cityofaustin/atd-data-tech/issues/8079

## Testing
**URL to test:** 

**Steps to test:**

---
#### Ship list
- [ ] Code reviewed 
- [ ] Product manager approved
- [ ] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#gid=776973707)

2022-01-13 21:27 UTC, mateoclarke approved these changes
🚢 💨 ✨

2022-01-13 21:27 UTC, mateoclarke commented on moped-editor/src/views/projects/projectView/ProjectFundingTable.js
> +                setSnackbarState({
Thanks for including this pattern, its really nice.

2022-01-13 21:27 UTC, mateoclarke commented on moped-editor/src/views/projects/projectView/ProjectFundingTable.js
> +              newData.funding_program_id || 0;
It's tedious that we have to do all this data cleaning but I don't know of a better solution. Just feels like a lot of extra boilerplate.

2022-01-14 04:26 UTC, amenity requested changes
Looks great, @sergiogcx ! Will you have the eCAPRIS field display "None" if it's blank like it does on the "Summary" tab?

2022-01-14 10:59 UTC, sergiogcx commented
@amenity ready for review again

2022-01-14 17:02 UTC, amenity commented
@sergiogcx - so sorry but I see that the mock up we had in the issue was inconsistent with our other designs. Can you please style the "eCAPRIS Subproject ID" text heading to match [that on the "Summary" tab](https://user-images.githubusercontent.com/1463708/149555083-28d54012-8b74-440d-8238-14e5a4338118.png) and remove the colon?

![Funding-tab-eCapris-task-order](https://user-images.githubusercontent.com/1463708/149555183-afb55647-a281-417e-aa9b-9a38985c4b77.png)

2022-01-14 17:30 UTC, sergiogcx commented
@amenity can you please check again?

<img width="571" alt="2022-01-14_11-30-11" src="https://user-images.githubusercontent.com/5282430/149559111-9a7bc35f-eed1-40c3-942f-75ff616e6057.png">

2022-01-14 17:43 UTC, amenity approved these changes
👌🙏🚢

2022-01-17 00:52 UTC, merged