Perform design refinements to advanced search
cityofaustin/atd-moped pull request #608
Opened 2022-03-22 15:07 UTC by chiaberry

## Associated issues

https://github.com/cityofaustin/atd-data-tech/issues/7402

## Testing
**URL to test:** 

https://7402-refine-search--atd-moped-main.netlify.app/moped/projects

**Steps to test:**

Shrink window down, the breakpoints have been shifted so it doesnt go to mobile until after the medium material UI breakpoint. (previously it was at large)

Also test the "no results" message in projects and staff, by putting nonsense in the search bar. 
![Screen Shot 2022-03-22 at 10 06 09 AM](https://user-images.githubusercontent.com/12474808/159513708-6d633e1e-693a-4e1d-a7d6-8654c0ca830f.png)

---
#### Ship list
- [x] Code reviewed 
- [x] Product manager approved
- [x] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable

2022-03-22 15:08 UTC, chiaberry commented on moped-editor/src/components/GridTable/GridTable.js
> +                        </TableRow>
This checks if there are no results and returns the appropriate message. 

The rest is indent changes because of the conditional.

2022-03-23 14:38 UTC, amenity requested changes
@chiaberry looking sharp!! Those breakpoints are so much better. 😊

I did notice that the search button pops over to the left at 1279px: 
<img width="1022" alt="Screen Shot 2022-03-23 at 9 30 24 AM" src="https://user-images.githubusercontent.com/1463708/159724612-07f4dcfb-8fed-4d01-be88-106e5324dd0f.png">

Also, I liked your suggestion to make this "No results" text centered. It's weird, it has that style in CSS but must be overridden in a parent div? 
<img width="1557" alt="Screen Shot 2022-03-23 at 9 31 05 AM" src="https://user-images.githubusercontent.com/1463708/159724693-35306e7a-7528-4cde-b86e-79590d06a50d.png">

2022-03-23 16:00 UTC, chiaberry commented
@amenity thanks for catching the jumpy search button! I've fixed both requests

2022-03-23 21:50 UTC, amenity approved these changes
💯  Perfection. Thanks!

2022-03-24 20:03 UTC, frankhereford approved these changes
Looks great. Code reviewed, and it behaved as expected on the pr netlify deployment. Thank you Chia!

I enjoyed getting to search for "nonsense" - thanks for the helpful instructions!
![nonsense-the-office-small](https://user-images.githubusercontent.com/3653206/160000572-b9ac373d-21fc-4ef9-ba00-f31f0c540ce5.gif)

2022-03-28 18:18 UTC, merged