removes project notes button and entry from projectNoteTypes array
cityofaustin/atd-moped pull request #621
Opened 2022-03-30 23:01 UTC by tillyw

## Associated issues
fixes https://github.com/cityofaustin/atd-data-tech/issues/8720

## Testing
**URL to test:** 

**Steps to test:**
go to a project, select comments tab

---
#### Ship list
- [ ] Code reviewed 
- [ ] Product manager approved
- [ ] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable

2022-03-31 19:05 UTC, frankhereford commented
Hi @tillyw - I edited your comment with a link to the netlify deployment for this PR. Just wanted to give you a heads up in case you wanted us to be testing in another environment - thanks!

2022-03-31 19:45 UTC, frankhereford requested changes
This isn't so much a request for changes, but more a request to see if the demonstrated behavior is a regression from this deletion or if it's something we had had prior. Thanks!

2022-03-31 19:45 UTC, frankhereford commented on moped-editor/src/views/projects/projectView/ProjectComments.js
> -            <CommentButton noteTypeId={3}>Timeline Notes</CommentButton>
I am wondering if there is code that requires this field to be on the page, or at least one with the `noteTypeId={3}`. I made a quick video to demonstrate it, and you can [find it here](https://austininnovation.slack.com/archives/CNUEPKLB1/p1648755790345859).  Thanks!

2022-04-01 22:03 UTC, mateoclarke approved these changes
🚢 💨 ✨

2022-04-05 04:06 UTC, amenity approved these changes
LGTM! ✨🙏

2022-04-05 16:23 UTC, frankhereford approved these changes

2022-04-05 16:24 UTC, merged