Add status update to Project List View
cityofaustin/atd-moped pull request #642
Opened 2022-05-03 15:05 UTC by chiaberry

## Associated issues

https://github.com/cityofaustin/atd-data-tech/issues/9044

Adds status update to columns as well as filtering. 

## Testing
**URL to test:** 

test locally or moped test. 

This branch branches off of the funding source branch, so if you deploy this branch and test, you will see both enhancements on the deployment. 

**Steps to test:**

https://moped-test.austinmobility.io/moped/projects/174?tab=summary

Add a status to the summary page. See it on the project list view. 

Another test to do is to add an internal note on the comments page and check that it does not show up as a status. 

---
#### Ship list
- [ ] Code reviewed 
- [ ] Product manager approved
- [ ] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable

2022-05-05 15:42 UTC, chiaberry commented on moped-database/migrations/1651513363000_alter_project_list_view_status/up.sql
> +      LIMIT 1)
lines 72-76

2022-05-09 15:33 UTC, frankhereford requested changes
I have tested this feature locally and it works great.

I have a change-request below regarding the query that defines the view. I think it may be able to be optimized by moving the subselect into the select clause propper.

However, I think it should be noted that at our scale, the optimization is only going to pick us up a few milliseconds. Pedantically, the query is maybe a magnitude slower than it was previously, but still clocking in at ~25 ms which is wicked fast.

2022-05-10 07:06 UTC, mateoclarke approved these changes
🚢 💨 ✨ 

I defer to Frank's suggestions, and just want to reiterate that I'm grateful for both of y'alls knowledge and persistence to implement, profile, optimize, and iterate on this view query.

2022-05-10 16:30 UTC, chiaberry commented on moped-database/migrations/1651513363000_alter_project_list_view_status/up.sql
> +      LIMIT 1)
I updated the query that defines the view. And after turning off JIT (https://github.com/cityofaustin/atd-moped/pull/648) it is going super quick. Thank you!

2022-05-10 19:42 UTC, frankhereford approved these changes

2022-05-16 14:10 UTC, patrickm02L requested changes
The status does not delete from the status column in the projects table once deleted in the other places it's been added. 

https://user-images.githubusercontent.com/5566727/168612051-bd64f177-6752-4941-99a1-745dea028d3f.mp4

2022-05-16 16:45 UTC, chiaberry commented on moped-database/migrations/1651513363000_alter_project_list_view_status/up.sql
> +      WHERE mpn.project_id = mp.project_id and mpn.project_note_type = 2 and mpn.status_id = 1
updated this line to also check that status has not been soft deleted.

2022-05-16 16:47 UTC, chiaberry commented
@patrickm02L similar issue as the previous PR, i wasn't checking for soft delete status. Updated the code to only get active status updates.

2022-05-16 18:26 UTC, merged

2022-05-16 23:17 UTC, mateoclarke commented
Added "Add a status update on the Summary tab. Verify it renders correctly in the Projects table" to the QA Script doc