Add new components to moped-components table
cityofaustin/atd-moped pull request #731
Opened 2022-07-25 20:18 UTC by chiaberry

## Associated issues

https://github.com/cityofaustin/atd-data-tech/issues/9795

## Testing
**URL to test:** 
Test locally or deploy to moped-test

**Steps to test:**

---
#### Ship list
- [ ] Code reviewed 
- [ ] Product manager approved
- [ ] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable

2022-07-26 17:13 UTC, mddilley approved these changes
Tested this locally, and I see all of the new components types. 👍 💡  🚌

2022-07-26 17:15 UTC, mddilley commented
@chiaberry I just caught the note about the **Project extent - generic** now being drawn as lines. Is that a change that happened in this PR?

2022-07-28 14:18 UTC, frankhereford commented on moped-database/migrations/1658526083849_insert_into_public_moped_components/up.sql
> +	(E'Transit', 1, E'Bus stop', false);
I always have to remind myself what Postgres Escape Notation `E''` does when I see it. It causes it to respect the usual suspects like `\n`, `\t` to get interpolated into the actual newline or tab character.

2022-07-29 16:57 UTC, johnclary commented on moped-database/migrations/1658526083849_insert_into_public_moped_components/up.sql
> +WHERE component_id = 0;
@mddilley here's where the Project Extent component is changing to line representation.

I'm pretty sure Chia checked, but I'll double check to see if we have any existing project extent components stored as points in the DB. We'd need to convert those to lines

2022-07-29 19:56 UTC, amenity requested changes
"Intersection lighting" should be a point, so give the user the ability to select an existing point or add a new one.

2022-08-01 16:55 UTC, johnclary commented
Looks like we currently have two projects in production using the **Project extent** component as points.

- [#246](https://mobility.austin.gov/moped/projects/246) - Looks like Fernando's project. Probably best to have them delete and re-add the extent component after we make this change
- [#159](https://mobility.austin.gov/moped/projects/159)  - This project was created and cancelled by Amenity - don't need to worry about it

2022-08-03 19:02 UTC, chiaberry commented
@amenity The bug where the drawing type is dictated by the type and not the subtype is fixed in this PR https://github.com/cityofaustin/atd-moped/pull/732. Because Street Lighting is drawn by lines, it overrides Intersection Lighting. The same thing happens right now in production for Highway type.

2022-08-03 19:15 UTC, amenity approved these changes
Now that I understand [PR #732](https://github.com/cityofaustin/atd-moped/pull/732) (thanks, @chiaberry !) I'm good to go on this.

2022-08-08 16:51 UTC, merged