Remove phase name from project list view
cityofaustin/atd-moped pull request #742
Opened 2022-08-08 16:57 UTC by chiaberry

## Associated issues

https://github.com/cityofaustin/atd-data-tech/issues/9350

## Testing
**URL to test:** 

**Steps to test:**

---
#### Ship list
- [ ] Code reviewed 
- [ ] Product manager approved
- [ ] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable

2022-08-08 20:10 UTC, chiaberry commented on moped-editor/src/queries/project.js
> +        phase_id
In this PR I learned that even if you don't explicitly list the field in the insert mutation, information included in the object being sent will still make its way into the database insertion

2022-08-09 15:16 UTC, johnclary commented on moped-database/views/project_list_view.sql
> -        AND phases.phase_name = 'construction'::text
i wonder if we might want to leave this as-is (matching on the `phase_name` text). it feels fragile to rely on the ID sequence.

2022-08-09 15:20 UTC, johnclary commented on moped-editor/src/views/projects/projectView/ProjectTimeline.js
> -                          phaseNameLookup[newData?.phase_id].toLowerCase(),
🚀

2022-08-09 15:20 UTC, johnclary commented on moped-editor/src/views/projects/projectView/ProjectTimeline.js
> -
🚀

2022-08-09 16:26 UTC, johnclary commented on moped-database/views/project_list_view.sql
> -        AND phases.phase_name = 'construction'::text
edit: ignore me! phase_name is not available, and i don't think we need to take the extra step of filtering on the `moped_phases.phase_name`

2022-08-10 18:41 UTC, frankhereford commented on moped-database/migrations/1658436152142_use_phase_ids_instead_of_names/up.sql
> +        AND phases.phase_id = 11 -- phase_id 11 is complete
I did confirm that these match the view in place on the test deployment.

2022-08-10 18:44 UTC, frankhereford requested changes
When I peeked this on its test deployment (https://9350-normal-phase--atd-moped-main.netlify.app/moped), I didn't see the start and end date displayed on the project listing page for the construction and completion phases I had added. I did make sure that the migrations and run too .. ✅

The current phase name did show up in the badge as expected.

Let me know if I'm missing something, I'll be happy to flip this to an approval if I'm out in left field.

2022-08-10 19:33 UTC, frankhereford approved these changes
![mybad](https://user-images.githubusercontent.com/3653206/184004152-465fe9f2-4e80-4497-a46a-3ffb4cabf7aa.gif)

Woops - my error! By testing it on test without the contents of [this PR #746](https://github.com/cityofaustin/atd-moped/pull/746), the test netlify deployment was connecting to staging's graphql endpoint.

This is A-OK - thank you @chiaberry!

2022-08-10 19:39 UTC, frankhereford commented
For the curious, this is deployed to test: https://9350-normal-phase--atd-moped-main.netlify.app/moped/projects

2022-08-11 16:26 UTC, patrickm02L approved these changes
Everything checks out! 🤘

https://user-images.githubusercontent.com/5566727/184182359-9a76697c-c08c-40d9-ae83-0a8a4535e53e.mp4

�

2022-08-11 16:58 UTC, merged

2022-08-11 17:08 UTC, mateoclarke reviewed
👍