Remove DO and contractor fields from summary page
cityofaustin/atd-moped pull request #747
Opened 2022-08-11 16:44 UTC by chiaberry

## Associated issues

First half of
https://github.com/cityofaustin/atd-data-tech/issues/9770 

Now that we have a contractor table, and will eventually be dropping these columns from the moped_project table, we should remove these fields from the summary page so users do not use deprecated fields. 

## Testing
**URL to test:** 

**Steps to test:**

The summary page should not give users an option to input contractor names or DO#. 

---
#### Ship list
- [ ] Code reviewed 
- [ ] Product manager approved
- [ ] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable

2022-08-11 16:50 UTC, chiaberry commented on moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummary.js
> +                <ProjectSummaryInterimID
I switched these around because the empty space was killing me.

2022-08-11 17:11 UTC, mateoclarke requested changes
This seems unrelated to your PR (maybe another recent merge to staging?) but I'm seeing this error in the Deploy Preview instance...

<img width="1464" alt="Screen Shot 2022-08-11 at 12 09 57 PM" src="https://user-images.githubusercontent.com/5697474/184193294-501cdea9-30a4-42f3-b8ea-92ee3d3287be.png">

2022-08-11 17:12 UTC, chiaberry commented
You are right! I just merged the other one to staging so I pulled main into this one. hopefully I've fixed it now

2022-08-11 17:32 UTC, mateoclarke approved these changes
🚢 💨 ✨

2022-08-11 20:41 UTC, patrickm02L approved these changes
Looks good. 🤘

<img width="2028" alt="Screen Shot 2022-08-11 at 3 40 30 PM" src="https://user-images.githubusercontent.com/5566727/184238321-d3103b39-1c03-4c2a-a709-a8ddae9e540a.png">

2022-08-12 16:49 UTC, johnclary approved these changes
🚢 🚢 🚢 🚢 🚢 🚢

2022-08-15 15:22 UTC, merged