10292 delete comment confirmation modal
cityofaustin/atd-moped pull request #815
Opened 2022-10-05 17:42 UTC by tillyw

## Associated issues
fixes https://github.com/cityofaustin/atd-data-tech/issues/10292
fixes https://github.com/cityofaustin/atd-data-tech/issues/10318

## Testing
**URL to test:** 

**Steps to test:**

---
#### Ship list
- [ ] Code reviewed 
- [ ] Product manager approved
- [ ] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable

2022-10-10 22:17 UTC, chiaberry reviewed
I like the idea of using a reusable confirmation modal, but agree with you that the conditionals and rendering inside the modal isn't that idea. The modal is tasked with displaying the tag content and I think theres a way we can get away from that. 

I've been thinking about it -- what if the modal's open/close state is tracked in the TagsSection and ProjectComments components. Clicking on the delete button will then toggle the modal to be open (which can be passed in as a prop). The modal component would then only be the Dialog.

2022-10-11 17:07 UTC, tillyw commented
> I like the idea of using a reusable confirmation modal, but agree with you that the conditionals and rendering inside the modal isn't that idea. The modal is tasked with displaying the tag content and I think theres a way we can get away from that.
> 
> I've been thinking about it -- what if the modal's open/close state is tracked in the TagsSection and ProjectComments components. Clicking on the delete button will then toggle the modal to be open (which can be passed in as a prop). The modal component would then only be the Dialog.

@chiaberry yes we can do it that way! that was how i initially had it, then i reworked it to have the modal fully contained within the component (including the open/close state) which i thought would be better for implementing it in other places, but maybe that's not ideal in this situation. i can rework it!

2022-10-11 21:50 UTC, tillyw commented
@chiaberry i reworked the modal to pass the state in from the parent component. it's a bit more complicated on the parent side but the modal is a lot simpler, hopefully this is an improvement!

2022-10-12 14:44 UTC, johnclary requested changes
@tillyw I've requested a few minor changes but on the whole this is great.

i definitely prefer this approach of passing the event handlers as props to modal component!  🙌

2022-10-12 14:44 UTC, johnclary commented on moped-editor/src/views/projects/projectView/DeleteConfirmationModal.js
> +            className={classes.deleteButton}
i believerthe MUI-preferred way to do this is to instead define the color within our theme so you can use the `color` prop. using the `color` prop will keep the hover/press/border styles consistent with other button components.

you can update our theme by copying [from here](https://github.com/cityofaustin/atd-moped/pull/824/files#diff-44937b1f7ff295c1e359f2a53ba72aa26f164bc292c836acb7e3cc0775934825) - which are the `error` colors i pulled from the MUI docs.

2022-10-12 14:44 UTC, johnclary commented on moped-editor/src/views/projects/projectView/DeleteConfirmationModal.js
> +          >
i've changed my mind—would mind putting the "Delete" button to the right of the "Cancel" button? That will match the "Delete project" modal, which feels right to me.

would you also switch the "Delete" button's variant to `contained`, and leave the "Cancel" button without a variant?

2022-10-13 15:47 UTC, roseeichelmann approved these changes
This looks and works great! I also like this updated solution of passing the open/close state into the modal from the parents rather than having the modal rendering the chip. Nice job ✨

2022-10-13 16:02 UTC, johnclary approved these changes
thank you @tillyw! 🙌  merging this....

2022-10-13 16:02 UTC, merged