displays project tags in projects list view
cityofaustin/atd-moped pull request #821
Opened 2022-10-06 20:33 UTC by tillyw

## Associated issues
https://github.com/cityofaustin/atd-data-tech/issues/10290

## Testing
**URL to test:** 

**Steps to test:**

---
#### Ship list
- [ ] Code reviewed 
- [ ] Product manager approved
- [ ] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable

2022-10-06 22:43 UTC, mddilley approved these changes
Works perfectly according to the test steps! ✨

2022-10-10 16:08 UTC, chiaberry commented on moped-editor/src/views/projects/projectsListView/ProjectsListViewExportConf.js
> +    label: "stcontract_numbersring",
☝🏼

2022-10-10 16:08 UTC, chiaberry requested changes
thanks for updating the export config, but there's a typo in the label

2022-10-10 19:42 UTC, roseeichelmann approved these changes
Tested with Netlify, it works as described! 🎃

2022-10-11 17:48 UTC, tillyw commented on moped-editor/src/views/projects/projectsListView/ProjectsListViewExportConf.js
> +    label: "stcontract_numbersring",
thanks for catching the typo!

2022-10-11 18:07 UTC, merged