Drops moped_proj_notes.added_by
cityofaustin/atd-moped pull request #935
Opened 2023-01-11 19:04 UTC by johnclary

## Associated issues
- https://github.com/cityofaustin/atd-data-tech/issues/11182

## Testing
**URL to test:** 

**Steps to test:**

---
#### Ship list
- [ ] Code reviewed 
- [ ] Product manager approved
- [ ] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable

2023-01-11 19:07 UTC, johnclary commented on moped-database/metadata/tables.yaml
> +        timeout: 60
Hasura did this. it's a new cloud-only feature.

2023-01-13 22:04 UTC, chiaberry requested changes
I can't edit or delete any of comments, which I have tracked down to 
` const editableComment =
                      userSessionData.user_id === item.added_by_user_id;` coming back as False

the COMMENTS_QUERY needs to return the added_by_user_id and then its all good

2023-01-17 22:26 UTC, frankhereford approved these changes
@chiaberry's comment is right on the money. I observed the same behavior, and when I added `added_by_user_id` to `COMMENT_QUERY` in `moped-editor/src/queries/comments.js#19, it worked like a charm. 

Given that change is in place, I was able to make, edit and delete comments. Thanks for this!

2023-01-18 15:16 UTC, johnclary commented
thanks @frankhereford and @chiaberry! i completely missed this :/

taking a closer look, i see we're defaulting the `added_by_user_id` column to `1` in the DB. i believe that value would just fail in production, but in any case i don't think we want a default value for this column. i'm going to spend a little more time thinking about how this—it won't make tomorrow's release.

2023-01-18 19:45 UTC, chiaberry approved these changes

2023-01-19 15:09 UTC, johnclary commented
turns out i've already broken comment editing in main (and prod?) thanks @chiaberry for patching this up!

2023-01-19 15:09 UTC, merged