adds project components activity log events
cityofaustin/atd-moped pull request #954
Opened 2023-01-25 19:40 UTC by tillyw

## Associated issues
fixes https://github.com/cityofaustin/atd-data-tech/issues/10806

## Testing
**URL to test:** 

**Steps to test:**

---
#### Ship list
- [ ] Code reviewed 
- [ ] Product manager approved
- [ ] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable

2023-01-26 17:54 UTC, mddilley submitted a review, later dismissed
Looks awesome! I added, edited, and removed and saw it all logged in the feed. 🗺️  🚀 

I think this is definitely outside of the scope of this issue, but it would be cool to log if the geometry of a component updated. Not sure what that would look like and maybe there is a backlog issue for it.

2023-01-26 17:54 UTC, mddilley commented on moped-editor/src/utils/activityLogFormatters/mopedMilestonesActivity.js
> +        { text: " as a new milestone", style: null },
🔍 🙌

2023-01-26 17:54 UTC, mddilley commented on moped-editor/src/utils/activityLogFormatters/mopedComponentsActivity.js
> +      changeText: [{ text: "Added a component: ", style: null }, componentText],
Noticed a `:` here and in the remove message that I didn't see anywhere else in the log. Gotta admit that I didn't look at every change type though!

2023-01-26 22:05 UTC, tillyw commented
> Member

thanks, @mddilley! i had the same thought and had a conversation with @johnclary before i submitted this for review and he said it's out of the scope of the issue but definitely something we should revisit! i do wonder if there is an issue for it

2023-01-26 22:27 UTC, chiaberry approved these changes
great! i agree that future enhancements will be good, but this is exactly what the issue requested

2023-01-26 22:42 UTC, roseeichelmann requested changes
when i choose a component that has a "x - x" pattern in the name, the full name doesn't show in the activity log. for example if i choose "Crosswalk - Creative", only "Crosswalk" shows. 
![image](https://user-images.githubusercontent.com/67130963/214967113-331bbda0-4a90-4a73-b93e-b41b5c69d0f5.png)

should this be adjusted to capture the full name?

2023-01-26 22:49 UTC, tillyw commented
> when i choose a component that has a "x - x" pattern in the name, the full name doesn't show in the activity log. for example if i choose "Crosswalk - Creative", only "Crosswalk" shows. ![image](https://user-images.githubusercontent.com/67130963/214967113-331bbda0-4a90-4a73-b93e-b41b5c69d0f5.png)
> 
> should this be adjusted to capture the full name?

thanks for catching this @roseeichelmann! I think this is a bug - I neglected to take into account a naming pattern for subcomponents. i will need to address this but i likely won't get to it until next week so i'm going to put this pr back into 'in progress' for now

2023-01-26 22:55 UTC, mddilley commented
> should this be adjusted to capture the full name?

@roseeichelmann @tillyw I should have called this out in my review because I thought the same thing. I found https://github.com/cityofaustin/atd-data-tech/issues/10807, and I think that covers this? Need to check with @johnclary

2023-01-26 23:30 UTC, tillyw commented
actually on further investigation the field we're not displaying is `component_subtype` which is part of the `moped_components` table - i just need to make sure to populate that when it exists! this isn't related to the `moped_subcomponents` table

2023-01-26 23:40 UTC, tillyw commented
@roseeichelmann @mddilley this was going to drive me crazy so i fixed it!
<img width="883" alt="Screen Shot 2023-01-26 at 5 37 18 PM" src="https://user-images.githubusercontent.com/35410637/214974543-7764bee7-895c-4000-890b-655308e7c1f4.png">
mike you still raise a good point about subcomponents - those don't display either. thanks for pulling up that issue - i'll be happy to add that next week.

2023-01-26 23:54 UTC, roseeichelmann approved these changes
you zapped that 🐛 so quick, looks beaut ✨

2023-01-27 15:38 UTC, johnclary approved these changes
Yep, we have follow up issues for subcomponents and map features:
- https://github.com/cityofaustin/atd-data-tech/issues/10809
- https://github.com/cityofaustin/atd-data-tech/issues/10807

It's going to be tricky to render meaningful information about these nested / many-many tables in the activity log. We'll have to query the related records out of the project and use them as a lookup. A fun challenge 🍿 

this looks fantastic @tillyw — thanks for getting the component subtype added in there 💯 ✨ 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🙌

2023-01-31 15:37 UTC, tillyw commented
thanks, all for the thorough reviews! and thanks, @johnclary for pointing me to those follow-up issues - that does sound like a fun challenge indeed 🤓

2023-01-31 15:37 UTC, merged