enhances project types activity log events
cityofaustin/atd-moped pull request #955
Opened 2023-01-25 23:45 UTC by tillyw

## Associated issues

## Testing
**URL to test:** 

**Steps to test:**

---
#### Ship list
- [ ] Code reviewed 
- [ ] Product manager approved
- [ ] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable

2023-01-27 15:57 UTC, johnclary requested changes
@tillyw this works exactly as promised :) :)


would you swap out the `BeenHere` icon for this `summarize` icon? That's the icon we use for misc project edits, like description?

```jsx
 <span className="material-symbols-outlined">summarize</span>
```

<img width="409" alt="Screen Shot 2023-01-27 at 10 54 17 AM" src="https://user-images.githubusercontent.com/14793120/215130090-ab1c2544-ff65-4980-b460-9f63a8c10aac.png">

2023-01-27 17:40 UTC, mddilley submitted a review, later dismissed
Tested locally, and this works beautifully! 👏 🚀 🎉  Gtg after the icon change that John requested

2023-01-27 17:40 UTC, mddilley commented on moped-editor/src/utils/activityLogFormatters/mopedProjectTypesActivity.js
> +  const entryMap = ProjectActivityLogTableMaps["moped_project_types"];
Ran this locally and noticed there is a compile warning that this var is never used. Might be used down the line but wanted to note that

2023-01-27 17:40 UTC, mddilley commented on moped-editor/src/utils/activityLogFormatters/mopedProjectTypesActivity.js
> +  // delete an existing component
Small change to this comment since this is for types

2023-01-31 22:05 UTC, tillyw commented
thanks, y'all, made these changes!

2023-01-31 22:32 UTC, johnclary approved these changes
🚢 🙌

2023-01-31 22:42 UTC, merged