Make column names in CSV download match column names in project list view
cityofaustin/atd-moped pull request #963
Opened 2023-02-01 20:02 UTC by mddilley

## Associated issues
https://github.com/cityofaustin/atd-data-tech/issues/11001

@johnclary - there are columns that we export that we don't show in the project list view. Think we should tidy those up too? Let me know if you have something specific in mind, and I'll update if needed. 🙏 

## Testing
**URL to test:** 

**Steps to test:**
1. Download the project list view CSV and take a look at the column names
2. Check to see that they match the names of the columns of the table in the app

---
#### Ship list
- [ ] Code reviewed 
- [ ] Product manager approved
- [ ] Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if applicable

2023-02-02 16:39 UTC, johnclary requested changes
@mddilley thanks for fixing these up and for pointing out the additional columns. Yes, let's go ahead and make proper labels for those:

- project_description -> Project Description
- current_phase_key -> Current Phase Key

I think those are the only two—let me know if I overlooked anything. Thanks again!

2023-02-02 16:50 UTC, johnclary approved these changes
🚢 🚢 🚢 🚢 🚢

2023-02-02 16:55 UTC, chiaberry approved these changes

2023-02-03 16:59 UTC, patrickm02L approved these changes
The csv column names are a lot cleaner! ✨

2023-02-03 17:21 UTC, merged